var F = Array();         //fotografies

F[1]="Joan Salvador.jpg";
F[2]="Salvadoriana.jpg";
F[3]="biblioteca.jpg";
F[4]="herbari2.jpg";
F[5]="pots.jpg";
F[6]="herbari.jpg";
F[7]="pomona.jpg";
F[8]="herbari.jpg";
F[9]="calaixos.jpg";
F[10]="Aristòtil.jpg";
F[11]="Plini.jpg";
F[12]="Tournefort.jpg";
F[13]="Pourret.jpg";
F[14]="Linné.jpg";


var C = Array(); 

C[01]="Arbre genealògic (sis generacions)<br>Els creadors de la col·lecció són les tres primeres generacions, Joan Salvador i Boscà (1598-1681), el seu fill  Jaume Salvador i Pedrol (1649-1725)  i els dos fills (Joan i Josep Salvador i Riera) l’activitat dels quals cobreix un segle i mig, del 1616 (apotecari)  al 1761. Les tres generacions successives continuaren enriquint la col·lecció durant un altre segle, encara que a ritme molt menor, però el més important, la varen mantenir oberta als estudiosos i als visitants."

C[02]="Gabinets de curiositats<br>Al segle XVI els nobles i persones benestants creaven col·leccions de tota mena animals, vegetals, minerals i fòssils. Algunes també incloïen obres d’art i peces arqueològiques. Aquestes col·leccions eren símbol de riquesa, i per això molts les obrien a  com a mostra del seu estatus social no és el cas  del gabinet Salvador ja que  la seva funció inicial era la de classificar i ordenar elements d'arreu del món per a la seva utilització com a remeis, els Salvador eren apotecaris i el seu afany era científic i no només col·leccionista."

C[03]="Biblioteca<br> El gabinet de curiositats es transforma en un laboratori de creació de coneixement en història natural quan disposa d’una biblioteca i un jardí.<br>La biblioteca era l’instrument per contrastar les observacions fetes amb allò que havien dit els clàssics<br><br> La biblioteca conté 1346 volums una de les majors col·leccions en mans laiques.La majoria obres de ciència publicades principalment entre 1478 i 1750, amb nombroses primeres edicions dels principals autors del Renaixement en els camps de la farmàcia, la botànica i la medicina, edicions de llibres de Plini el Vell i Aristòtil sobre ciència natural.<br>Multilingüisme en llatí més de la meitat, però també italià, francès, anglès, alemany i portuguès a més de castellà i català."

C[04]="Herbari<br>Exemplars del regne vegetal conservats als plecs de l’herbari, l’herbari és un dels més antics i ben documentats d’Espanya (4.917 exemplars) ordenats segon el sistema del botànic Joseph Pitton de Tournefort, condeixeble de Jaume a  Montpeller i mestre de Joan.<br>En una de les estades de Pierre André Pourret (1754 - 1818) a Barcelona va afegir la els noms segons la classificació linneana que ja era acceptada per la gran majoria de naturalistes.<br>Els Salvadors anotaven la procedència de tots els exemplars, aquesta precisió ha permès la utilització científica de l’herbari, moltes de les localitzacions de plantes de les rodalies de Barcelona es troben actualment extingides."

C[05]="Pots de productes<br>Mes de quatre cents pots de vidre amb -simples medicinals- elements procedents de qualsevol dels regnes de la natura amb ús medicinal.<br>Els Salvador tenien força prestigi, tots els metges de la ciutat, fins i tot d’altres ciutats, confiaven en el seu rigor a l’hora de preparar fórmules magistrals per guarir els seus pacients. El que no tenien els Salvador era molt difícil de trobar.<br>Les apotecaries eren laboratoris de productes medicinals. L’ofici d’apotecari era el coneixement i l’ús de nombrosos productes naturals, anomenats simples medicinals, d’origen animal, mineral i sobretot vegetal. Un medicament s’elaborava a partir dels simples combinats amb diferents fórmules i sota diverses formes, hi havia una reglamentació per fer-ho és deia Les Concòrdies<br>Les Concòrdies de Barcelona són les diferents edicions de la farmacopea vigent al Principat de Catalunya des del 1511 fins al 1794. Es considera la segona farmacopea del món, després de la de Florència.<br>El 29 d'agost del 1510, Ferran el Catòlic va concedir el primer reial privilegi al Col·legi d'Apotecaris de Barcelona amb objecte d'uniformitzar les preparacions farmacèutiques. Els convenis dels apotecaris eren exposats a les consideracions del Col·legi de Doctors en Medecina de Barcelona, d'on prové en nom de concòrdies. A les Concòrdies s'hi troben 370 fórmules que apleguen 617 drogues d'opiates, electuaris i llepadums, pastilles, loocs, conserves, xarops i arrops, infusions i coccions, píndoles, laxants, pólvores, col·liris, olis, ungüents, cerats i emplastres. Predominen les del regne vegetal: 513, mentre que 46 són del regne mineral i 58 del regne animal."

C[06]="Les tertúlies eren un espai d’intercanvi de coneixements, resultats experimentals, teories i projectes científics.<br>A la rebotiga dels Salvador es reunien diversos membres de la família amb ciutadans aficionats a les ciències naturals, d’altres apotecaris, metges i cirurgians tan barcelonins com de pas per la ciutat. Cal destacar les tertúlies que durant la guerra de Successió (1705-1714) metges, cirurgians i naturalistes que acompanyaven els exercits.<br>La tardor del 1706, la rebotiga es convertia en una improvisada acadèmia, amb tertúlies amb els metges i cirurgians dels vaixells ancorats a Barcelona."

C[07]="Les col·leccions del gabinet Salvador es poden classificar en Naturalia i Artificialia<br>Naturalia  objectes considerats de creació divina.<br>Artificialia objectes produïts pels humans.<br> Naturalia<br> Calaixos amb material malacològics; més d’un miler d’exemplars de closques i petxines de variada procedència. La col·lecció de fustes, segons la documentació, superava els 500 exemplars, es considera perduda. La col·lecció de llavors es conserva en bona part i és el resultat de l’intens intercanvi entre els Salvadors i altres naturalistes europeus. Llavors preuades per les propietats medicinals, l’origen exòtic, la forma.<br>Petrifactes (fòssils) <br> El caràcter natural o artificial dels petrifactes (fòssils) era objecte de controvèrsia en les discussions científiques de l’època.<br> Artificialia  El gabinet contenia gravats, pintures, armes, instruments, monedes, medalles i antiguitats però no ens ha arribat res de tot això.<br>De Artificiala es conserven les terres segellades i les reproduccions de fruites.<br>Les virtuts terapèutiques deriven de les terres amb que estaven fets, però també atribuïen propietats als símbols gravats.<br>Pomones reproduccions escultòriques de fruits amb mides i colors naturals, fetes amb materials diversos guix, cartró, ceràmica i porcellana. La idea era replegar el mostrari complert dels fruits i fruites cultivades a Espanya (Pomona espanyola) el 1856 la col·lecció contenia més de 400 exemplars."

C[08]="La correspondència era essencial en la comunicació científica, acompanyaven les cartes llistes d’espècimens requerits o oferts, dibuixos, pintures o gravats d’animals o plantes, plecs d’herbari, llavors. Els Salvadors mantingueren correspondència amb naturalistes del Principat, Península Ibèrica, França, Itàlia, Amsterdam, Londres, Viena."

C[09]="Els gabinets de curiositats són els precedents dels museus moderns, de fet, es considera el Gabinet Salvador com el primer museu de Barcelona. <br>El Gabinet Salvador és una de les poques col·leccions europees d'història natural que no s'ha dispersat i que està localitzada en la pràctica totalitat. Una col·lecció de curiositats naturals i una biblioteca científica, mèdica i farmacèutica que és, en la seva matèria, una de les més importants del món.<br> És un dels pocs gabinets científics que ha arribat als nostres dies –la majoria van desaparèixer bé integrats en els grans museus nacionals del segle XIX, bé dispersats pel pas del temps i la història- i que es manté pràcticament íntegre.<br>Josep Salvador i Soler (1804-1855).<br>Mort prematurament en un tràgic accident, quan els seus fills eren encara menors d'edat, els tutors d'aquests van decidir traslladar les col·leccions al gran mas de la Bleda, Santa Margarida i els Monjos (Alt Penedès). D'allí, les va rescatar, vuitanta anys més tard, Pius Font i Quer per dipositar-les a l'Institut Botànic de Barcelona, que la Generalitat acabava de crear.<br>En celebrar la exposició Salvadoriana es va complementar la col·lecció adquirint un conjunt de llibres, objectes i documentació, nou caixes amb més de cinc-centes peces i mil documents que encara es trobaven al mas de la Bleda."

C[10 ]="Aristòtil (Estagira, Grècia, 384 aC - Eubea, Grècia, 322 aC) va ser un filòsof de l'Antiga Grècia. Se'l considera com un dels grans pensadors de la humanitat. La seva lògica, naturalisme i ètica dominaren en el pensament europeu durant gairebé 2.000 anys, fins ben entrat el segle XVI. Aristòtil va dominar el coneixement de la seva època, des de la filosofia a la biologia, des de les matemàtiques fins a la psicologia. No sols va estudiar gairebé tots els àmbits del coneixement existents en el seu temps, sinó que, a més, va fer contribucions significatives en la majoria d'aquests."

C[11]="Plini el Vell, o Gai Plini Segon (Como, Itàlia, any 23 - Estàbia, 25 d'agost de 79), va ser un escriptor llatí, científic, naturalista i militar romà. És conegut principalment per la seva obra Naturalis Historia i per l'episodi de la seva mort, Plini el Vell va morir l’any 79 durant l’erupció del Vesubi, un volcà que sepultà Pompeia, Herculà i Estàbia"

C[12]="Joseph Pitton de Tournefort, condeixeble de Jaume a  Montpeller i mestre de Joan. botànic i metge.<br>El 1694 publica la seva primera obra -Éléments de botanique ou méthode pour connaître les plantes- en tres volums. Obra basada en l'estructura de les flors i els fruits."

C[13]="Pierre André Pourret (1754 - 1818) clergue i botànic francés, en una de les estades a Barcelona va afegir al herbari els noms segons la classificació linneana que ja era acceptada per la gran majoria de naturalistes."

C[14]="Carl von Linné (23 de maig del 1707-10 de gener de 1778), fou un botànic, científic, metge i zoòleg suec que establí els fonaments del sistema modern de la nomenclatura binomial. És considerat el pare de la taxonomia moderna i conegut com un dels pares de l'ecologia moderna.<br>El 1753, Linné publicà Species Plantarum, un treball acceptat internacionalment com el començament de la nomenclatura botànica moderna, juntament amb la seva gran obra anterior, Systema Naturae. El llibre descrivia més de 7.300 espècies."